### PR TITLE
Enable deleting slides

### PR DESCRIPTION
**Pull request by MilosStanic**
Please merge this pull request to enable deleting slides from backend.

### CODE REVIEW

**Comment by getrightnl** [comment]
Merged 👍  @MilosStanic

**Comment by getrightnl** [comment]
Dunno if we have to change the update number in the version.yaml

**Comment by MilosStanic** [comment]
Oh, well, most probably, otherwise, I think the users will have no clue there is a new version they should pull. 
Meanwhile, in my own copy of your plugin, I have enabled reordering of slides, showing slide thumbnail in the backend slides list, and enabling/disabling thumbnails with ajax switch from the list of thumbnails. 
These are all useful additions to the plugin. However, I'm not very skillful with github so it's really lot of trouble for me to make a pull request now. If you want me I can send you zipped my version of your plugin and then you can compare and add the features if you find them useful. 

Thanks.

**Comment by getrightnl** [comment]
@MilosStanic If you want to do that please :) Glad you are willing to help. I will update version.yaml and check if the backend says that there is a new update

**Comment by MilosStanic** [comment]
Here it is. 
One more thing, I also commented out the line 66 in Plugin.php so it will show in the permissions settings for users, and changed the setting name in lines 69-71

[getright.zip](https://github.com/getrightnl/octobercms-slider-plugin/files/1688875/getright.zip)

**Comment by MilosStanic** [comment]
yes, to enable reordering, you have to add column `sort_order` as type integer, default 0, to the `getright_slider_slides` table.

**Comment by getrightnl** [comment]
@MilosStanic Is it in a migration?

**Comment by MilosStanic** [comment]
It's not. That's why I'm telling you here. 

And to enable the feature of enabled/disabled, I added column `enabled` as tiny int.

**Comment by getrightnl** [comment]
Okay! I will have a look thanks for the suggestions. Will have look and probably make migrations for it.

**Pull request merged**
